/* eslint-disable react/prop-types */
import Carousel from "./Carousel";

const SeriesOffer = ({title}) => {
    const film = [
        {
            title: "Premium Show 1",
            url: "/img/series-chill-film/film 1.png",
            slug:"premium",
            status: "Premium",
            year: 2021,
            duration: "2h 30m",
            genre: "Action, Adventure",
            cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
            synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
            episodes: null,
            rekomendasi: [
                {
                    title: "Premium Show 1",
                    url: "/img/trending-film/film 1.png",
                    ratingTop: "Top 10",
                    slug:"premium",
                    status: "Premium",
                    year: 2021,
                    duration: "2h 30m",
                    genre: "Action, Adventure",
                    cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    episodes: null,
                },
                {
                    title: "Premium Show 2",
                    url: "/img/series-chill-film/film 5.png",
                    ratingTop: "Top 10",
                    year: 2023,
                    duration: "2h 5m",
                    genre: "Horror, Mystery",
                    cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    episodes: null,
                },
                {
                    title: "Lorem ipsum dolor",
                    url: "/img/trending-film/film 4.png",
                    ratingTop: "Top 10",
                    duration: "47 min",
                    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum",
                },
            ],
        },
        {
            title: "Premium Show 2",
            url: "/img/series-chill-film/film 2.png",
            slug:"premium",
            status: "Premium",
            year: 2022,
            duration: "1h 45m",
            genre: "Comedy, Drama",
            cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
            synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
            episodes: null,
            rekomendasi: [
                {
                    title: "Premium Show 1",
                    url: "/img/trending-film/film 1.png",
                    ratingTop: "Top 10",
                    slug:"premium",
                    status: "Premium",
                    year: 2021,
                    duration: "2h 30m",
                    genre: "Action, Adventure",
                    cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    episodes: null,
                },
                {
                    title: "Premium Show 2",
                    url: "/img/series-chill-film/film 5.png",
                    ratingTop: "Top 10",
                    year: 2023,
                    duration: "2h 5m",
                    genre: "Horror, Mystery",
                    cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    episodes: null,
                },
                {
                    title: "Lorem ipsum dolor",
                    url: "/img/trending-film/film 4.png",
                    ratingTop: "Top 10",
                    duration: "47 min",
                    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum",
                },
            ],
        },
        {
            title: "Premium Show 3",
            url: "/img/series-chill-film/film 3.png",
            slug:"premium",
            status: "Premium",
            year: 2023,
            duration: "2h 15m",
            genre: "Drama, Thriller",
            cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
            synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
            episodes: null,
            rekomendasi: [
                {
                    title: "Premium Show 1",
                    url: "/img/trending-film/film 1.png",
                    ratingTop: "Top 10",
                    slug:"premium",
                    status: "Premium",
                    year: 2021,
                    duration: "2h 30m",
                    genre: "Action, Adventure",
                    cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    episodes: null,
                },
                {
                    title: "Premium Show 2",
                    url: "/img/series-chill-film/film 5.png",
                    ratingTop: "Top 10",
                    year: 2023,
                    duration: "2h 5m",
                    genre: "Horror, Mystery",
                    cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    episodes: null,
                },
                {
                    title: "Lorem ipsum dolor",
                    url: "/img/trending-film/film 4.png",
                    ratingTop: "Top 10",
                    duration: "47 min",
                    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum",
                },
            ],
        },
        {
            title: "Premium Show 4",
            url: "/img/series-chill-film/film 4.png",
            slug:"premium",
            status: "Premium",
            year: 2022,
            duration: "1h 55m",
            genre: "Sci-Fi, Fantasy",
            cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
            synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
            episodes: null,
            rekomendasi: [
                {
                    title: "Premium Show 1",
                    url: "/img/trending-film/film 1.png",
                    ratingTop: "Top 10",
                    slug:"premium",
                    status: "Premium",
                    year: 2021,
                    duration: "2h 30m",
                    genre: "Action, Adventure",
                    cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    episodes: null,
                },
                {
                    title: "Premium Show 2",
                    url: "/img/series-chill-film/film 5.png",
                    ratingTop: "Top 10",
                    year: 2023,
                    duration: "2h 5m",
                    genre: "Horror, Mystery",
                    cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    episodes: null,
                },
                {
                    title: "Lorem ipsum dolor",
                    url: "/img/trending-film/film 4.png",
                    ratingTop: "Top 10",
                    duration: "47 min",
                    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum",
                },
            ],
        },
        {
            title: "Premium Show 5",
            url: "/img/series-chill-film/film 5.png",
            slug:"premium",
            status: "Premium",
            year: 2023,
            duration: "2h 5m",
            genre: "Horror, Mystery",
            cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
            synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
            episodes: null,
            rekomendasi: [
                {
                    title: "Premium Show 1",
                    url: "/img/trending-film/film 1.png",
                    ratingTop: "Top 10",
                    slug:"premium",
                    status: "Premium",
                    year: 2021,
                    duration: "2h 30m",
                    genre: "Action, Adventure",
                    cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    episodes: null,
                },
                {
                    title: "Premium Show 2",
                    url: "/img/series-chill-film/film 5.png",
                    ratingTop: "Top 10",
                    year: 2023,
                    duration: "2h 5m",
                    genre: "Horror, Mystery",
                    cast: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    synopsis: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum.",
                    episodes: null,
                },
                {
                    title: "Lorem ipsum dolor",
                    url: "/img/trending-film/film 4.png",
                    ratingTop: "Top 10",
                    duration: "47 min",
                    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum",
                },
            ],
        },
    ];

    const settings = {
        infinite: true,
        speed: 500,
        slidesToShow: 5,
        slidesToScroll: 1,
        arrows: true,
        nextArrow: <button className="next-arrow">→</button>,
        prevArrow: <button className="prev-arrow">←</button>,
        responsive: [
            {
                breakpoint: 768,
                settings: {
                    slidesToShow: 3.5,
                    slidesToScroll: 1,
                    arrows: true,
                },
            },
            {
                breakpoint: 480,
                settings: {
                    slidesToShow: 3.1,
                    slidesToScroll: 1,
                    arrows: true,
                },
            },
        ],
    };

    return (
        <div>
            <Carousel title={title} items={film} settings={settings} />
        </div>
    );
};

export default SeriesOffer;
